// Generated by tools/tts.py - do not edit by hand.
window.TIMELINE = {
 "duration": 478.4,
 "scenes": [
  {
   "id": "hook",
   "start": 0.0,
   "end": 36.767,
   "lines": [
    {
     "text": "Right now, while you watch this, something astonishing is happening inside you.",
     "start": 1.2,
     "end": 5.424
    },
    {
     "text": "In your skin, in your gut, and deep inside your bones, cells are tearing themselves in half.",
     "start": 5.774,
     "end": 10.851
    },
    {
     "text": "Every second, your body makes around four million new cells.",
     "start": 11.201,
     "end": 14.529
    },
    {
     "text": "And not one of them is built from scratch. Every new cell comes from an old cell splitting in two.",
     "start": 14.879,
     "end": 20.191
    },
    {
     "text": "This is mitosis. It's how you grew from a single cell into more than thirty trillion, and how your body keeps itself alive today.",
     "start": 20.541,
     "end": 27.987
    },
    {
     "text": "So how does a cell copy itself, without making a mess of its own instructions?",
     "start": 28.337,
     "end": 32.667
    }
   ]
  },
  {
   "id": "cell",
   "start": 36.767,
   "end": 105.047,
   "lines": [
    {
     "text": "Let's meet our hero: a somatic cell.",
     "start": 37.167,
     "end": 39.386
    },
    {
     "text": "Soma is Greek for body, so somatic cells are simply body cells: skin cells, muscle cells, liver cells.",
     "start": 39.736,
     "end": 46.627
    },
    {
     "text": "Basically every cell in you, except sperm and egg cells, which are made by a different process called meiosis.",
     "start": 46.977,
     "end": 53.355
    },
    {
     "text": "Our cell is filled with cytoplasm, a jelly-like soup where the cell's tiny machines float around, doing the work of staying alive.",
     "start": 53.705,
     "end": 61.556
    },
    {
     "text": "In the middle sits the nucleus, the control centre, wrapped in a double-layered membrane called the nuclear envelope.",
     "start": 61.906,
     "end": 68.327
    },
    {
     "text": "Inside the nucleus is the most precious thing the cell owns: its DNA.",
     "start": 68.677,
     "end": 72.923
    },
    {
     "text": "Most of the time, the DNA doesn't look like the neat X-shapes from your textbook. It's a loose, tangled mass called chromatin: DNA wound around little proteins, like thread around spools.",
     "start": 73.273,
     "end": 84.835
    },
    {
     "text": "And there is a lot of it. Unravel the DNA from just one of your cells, and it would stretch about two metres, all packed into a nucleus far smaller than the width of a hair.",
     "start": 85.185,
     "end": 95.212
    },
    {
     "text": "In humans, that DNA is split into forty-six pieces, called chromosomes. Twenty-three from your mother, and twenty-three from your father.",
     "start": 95.562,
     "end": 103.797
    }
   ]
  },
  {
   "id": "cycle",
   "start": 105.047,
   "end": 145.985,
   "lines": [
    {
     "text": "A cell's life follows a loop called the cell cycle. Think of it as a clock with two very unequal parts.",
     "start": 105.447,
     "end": 111.612
    },
    {
     "text": "The long part is interphase, where the cell grows and prepares. The short part is the mitotic phase, where the cell actually divides.",
     "start": 111.962,
     "end": 120.367
    },
    {
     "text": "For a human cell that divides about once a day, interphase takes around twenty-three hours. Mitosis itself? About one hour.",
     "start": 120.717,
     "end": 128.397
    },
    {
     "text": "So if cells had social media, almost every post would just say: still preparing.",
     "start": 128.747,
     "end": 133.505
    },
    {
     "text": "Some cells, like the ones lining your gut, race around this cycle again and again. Others, like most of the nerve cells in your brain, step off the cycle and may never divide again.",
     "start": 133.855,
     "end": 144.735
    }
   ]
  },
  {
   "id": "interphase",
   "start": 145.985,
   "end": 199.152,
   "lines": [
    {
     "text": "Let's zoom into interphase. Despite the name, it isn't a break. It's the busiest time of the cell's life.",
     "start": 146.385,
     "end": 152.422
    },
    {
     "text": "First comes G1, the first growth phase. The cell gets bigger, builds proteins, and makes more of its tiny organelles.",
     "start": 152.772,
     "end": 160.367
    },
    {
     "text": "Then comes the S phase, S for synthesis, where the cell copies its entire DNA.",
     "start": 160.717,
     "end": 165.858
    },
    {
     "text": "That's about six billion DNA letters, copied in a few hours, with only around one mistake per billion letters. Like copying out a library of thousands of books by hand, and making only a handful of typos.",
     "start": 166.208,
     "end": 179.264
    },
    {
     "text": "Each chromosome is now doubled. The two identical copies, called sister chromatids, stay joined at a point called the centromere.",
     "start": 179.614,
     "end": 187.422
    },
    {
     "text": "Finally, in G2, the cell grows a little more and checks its work. Only if the DNA is copied and undamaged does the cell get the green light.",
     "start": 187.772,
     "end": 197.052
    }
   ]
  },
  {
   "id": "mitosis",
   "start": 199.152,
   "end": 223.443,
   "lines": [
    {
     "text": "And now, the main event: mitosis. The name comes from the Greek word mitos, meaning thread, because when scientists first watched it under microscopes in the 1880s, the chromosomes looked like threads.",
     "start": 199.552,
     "end": 212.352
    },
    {
     "text": "Mitosis has four stages, and there's an easy way to remember them: PMAT.",
     "start": 212.702,
     "end": 218.313
    },
    {
     "text": "Prophase. Metaphase. Anaphase. Telophase.",
     "start": 218.663,
     "end": 221.543
    }
   ]
  },
  {
   "id": "prophase",
   "start": 223.443,
   "end": 260.532,
   "lines": [
    {
     "text": "Prophase. Pro means before. This is where the cell packs for the big move.",
     "start": 223.843,
     "end": 228.131
    },
    {
     "text": "The loose chromatin coils up, tighter and tighter, until each chromosome becomes a short, thick X-shape. It's like turning a heap of tangled headphone cables into neatly wound bundles. Much easier to move.",
     "start": 228.481,
     "end": 241.473
    },
    {
     "text": "Meanwhile, at opposite ends of the cell, structures called centrosomes start building long ropes made of protein. These are the spindle fibers.",
     "start": 241.823,
     "end": 250.335
    },
    {
     "text": "And then, the nuclear envelope, the wall that protected the DNA, breaks apart. The chromosomes are now floating free in the cytoplasm.",
     "start": 250.685,
     "end": 259.282
    }
   ]
  },
  {
   "id": "metaphase",
   "start": 260.532,
   "end": 288.469,
   "lines": [
    {
     "text": "Metaphase. Think M for middle.",
     "start": 260.932,
     "end": 262.916
    },
    {
     "text": "Spindle fibers reach out from both ends of the cell, grab each chromosome at its centromere, and pull.",
     "start": 263.266,
     "end": 269.261
    },
    {
     "text": "Tugged equally from both sides, the chromosomes line up in a single row across the middle of the cell.",
     "start": 269.611,
     "end": 275.349
    },
    {
     "text": "This is the cell's most important safety check. If even one chromosome isn't properly attached, everything waits. A mistake here could leave a daughter cell with missing or extra instructions.",
     "start": 275.699,
     "end": 287.219
    }
   ]
  },
  {
   "id": "anaphase",
   "start": 288.469,
   "end": 314.167,
   "lines": [
    {
     "text": "Anaphase. Think A for apart.",
     "start": 288.869,
     "end": 290.619
    },
    {
     "text": "Suddenly, the glue holding the sister chromatids together dissolves, and the spindle fibers shorten, reeling the chromatids towards opposite ends of the cell.",
     "start": 290.969,
     "end": 300.249
    },
    {
     "text": "Each end of the cell now receives an identical, complete set of chromosomes.",
     "start": 300.599,
     "end": 305.271
    },
    {
     "text": "They travel at about one thousandth of a millimetre per minute. Slow for us, but for a cell, it's a dramatic tug of war.",
     "start": 305.621,
     "end": 312.917
    }
   ]
  },
  {
   "id": "telophase",
   "start": 314.167,
   "end": 336.856,
   "lines": [
    {
     "text": "Telophase. Telo means end.",
     "start": 314.567,
     "end": 316.444
    },
    {
     "text": "The chromosomes arrive at the poles, and everything from prophase runs in reverse. A new nuclear envelope forms around each set.",
     "start": 316.794,
     "end": 324.901
    },
    {
     "text": "The chromosomes relax and uncoil back into chromatin, and the spindle fibers are taken apart and recycled.",
     "start": 325.251,
     "end": 331.928
    },
    {
     "text": "For a brief moment, one cell holds two complete nuclei.",
     "start": 332.278,
     "end": 335.606
    }
   ]
  },
  {
   "id": "cytokinesis",
   "start": 336.856,
   "end": 367.654,
   "lines": [
    {
     "text": "But we're not done yet. The cell still has to split its body in two. This final step is called cytokinesis: cyto meaning cell, and kinesis meaning movement.",
     "start": 337.256,
     "end": 347.176
    },
    {
     "text": "In animal cells, a ring of protein tightens around the middle like a drawstring, pinching the cytoplasm in two.",
     "start": 347.526,
     "end": 354.161
    },
    {
     "text": "Plant cells have a stiff cell wall, so they can't pinch. Instead, they build a brand new wall right down the middle, called the cell plate.",
     "start": 354.511,
     "end": 362.02
    },
    {
     "text": "And there they are. One parent cell has become two daughter cells.",
     "start": 362.37,
     "end": 365.954
    }
   ]
  },
  {
   "id": "daughters",
   "start": 367.654,
   "end": 402.631,
   "lines": [
    {
     "text": "Each daughter cell is genetically identical to the parent cell, with the same forty-six chromosomes and the same instructions. They're clones.",
     "start": 368.054,
     "end": 376.481
    },
    {
     "text": "Each one is a bit smaller than the parent, so it starts back at G1, growing and preparing to go around the cell cycle again.",
     "start": 376.831,
     "end": 384.233
    },
    {
     "text": "That's why mitosis is perfect for growth, and for repair. When you scrape your knee, it's mitosis that fills the gap with fresh new skin cells.",
     "start": 384.583,
     "end": 393.074
    },
    {
     "text": "The lining of your gut is replaced every few days. Your outer skin, roughly every month. A lot of you is much newer than you think.",
     "start": 393.424,
     "end": 401.381
    }
   ]
  },
  {
   "id": "wrong",
   "start": 402.631,
   "end": 424.949,
   "lines": [
    {
     "text": "Of course, a process this powerful needs strict rules. Those safety checks act like brakes on the cell cycle.",
     "start": 403.031,
     "end": 409.453
    },
    {
     "text": "When the brakes fail, cells can start dividing out of control, ignoring every stop sign. That's what happens in cancer.",
     "start": 409.803,
     "end": 416.907
    },
    {
     "text": "Some cancer medicines fight back by jamming the spindle fibers, so the runaway cells can't finish mitosis.",
     "start": 417.257,
     "end": 423.699
    }
   ]
  },
  {
   "id": "recap",
   "start": 424.949,
   "end": 454.245,
   "lines": [
    {
     "text": "So, let's recap.",
     "start": 425.349,
     "end": 426.48
    },
    {
     "text": "Interphase: the cell grows and copies its DNA.",
     "start": 426.83,
     "end": 429.774
    },
    {
     "text": "Prophase: chromatin condenses into chromosomes, spindle fibers form, and the nuclear envelope breaks down.",
     "start": 430.124,
     "end": 437.079
    },
    {
     "text": "Metaphase: the chromosomes line up in the middle.",
     "start": 437.429,
     "end": 440.053
    },
    {
     "text": "Anaphase: the sister chromatids are pulled apart.",
     "start": 440.403,
     "end": 443.219
    },
    {
     "text": "Telophase: two new nuclei form.",
     "start": 443.569,
     "end": 445.574
    },
    {
     "text": "And cytokinesis: the cytoplasm divides, and one parent cell becomes two identical daughter cells.",
     "start": 445.924,
     "end": 452.345
    }
   ]
  },
  {
   "id": "outro",
   "start": 454.245,
   "end": 478.4,
   "lines": [
    {
     "text": "You started life as a single cell, smaller than the full stop at the end of a sentence.",
     "start": 454.645,
     "end": 459.339
    },
    {
     "text": "Copy. Line up. Pull apart. Split. Repeated again and again, trillions of times.",
     "start": 459.689,
     "end": 464.51
    },
    {
     "text": "Every cell in your body is a copy of a copy of a copy of that very first one. And it all comes down to four letters: P, M, A, T.",
     "start": 464.86,
     "end": 473.5
    }
   ]
  }
 ]
};
