"""Generate the narration with Kokoro TTS and build the shared timeline.

Usage: python3 tools/tts.py <kokoro.onnx> <voices.npz>

Outputs:
  build/lines/*.wav      one clip per narration line (cached by text hash)
  build/narration.wav    all clips placed on the timeline
  timeline.js            scene + line timings, read by animation.html
  captions.srt           subtitles
"""
import hashlib, json, os, sys, wave
import numpy as np
from kokoro_onnx import Kokoro

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SR = 24000


def write_wav(path, samples):
    pcm = (np.clip(samples, -1, 1) * 32767).astype(np.int16)
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm.tobytes())


def read_wav(path):
    with wave.open(path) as w:
        return np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16).astype(np.float32) / 32767


def srt_time(t):
    ms = int(round(t * 1000))
    h, ms = divmod(ms, 3600000)
    m, ms = divmod(ms, 60000)
    s, ms = divmod(ms, 1000)
    return f"{h:02}:{m:02}:{s:02},{ms:03}"


def main(model, voices):
    spec = json.load(open(os.path.join(HERE, "narration.json")))
    lines_dir = os.path.join(HERE, "build", "lines")
    os.makedirs(lines_dir, exist_ok=True)
    tts = None

    t = 0.0
    scenes, clips = [], []
    for scene in spec["scenes"]:
        start = t
        t += scene.get("lead", 0.4)
        lines = []
        for line in scene["lines"]:
            say = line.get("say", line["text"])
            key = hashlib.sha1(f'{spec["voice"]}|{spec["speed"]}|{say}'.encode()).hexdigest()[:16]
            path = os.path.join(lines_dir, key + ".wav")
            if not os.path.exists(path):
                tts = tts or Kokoro(model, voices)
                samples, sr = tts.create(say, voice=spec["voice"], speed=spec["speed"], lang="en-us")
                assert sr == SR
                write_wav(path, samples)
                print(f"  tts {scene['id']}: {say[:60]}", flush=True)
            audio = read_wav(path)
            dur = len(audio) / SR
            lines.append({"text": line["text"], "start": round(t, 3), "end": round(t + dur, 3)})
            clips.append((t, audio))
            t += dur + line.get("gap", spec["lineGap"])
        t += spec["sceneGap"]
        scenes.append({"id": scene["id"], "start": round(start, 3), "end": round(t, 3), "lines": lines})

    total = round(t, 3)
    mix = np.zeros(int(total * SR) + SR, dtype=np.float32)
    for at, audio in clips:
        i = int(at * SR)
        mix[i:i + len(audio)] += audio
    write_wav(os.path.join(HERE, "build", "narration.wav"), mix[: int(total * SR)])

    timeline = {"duration": total, "scenes": scenes}
    with open(os.path.join(HERE, "timeline.js"), "w") as f:
        f.write("// Generated by tools/tts.py - do not edit by hand.\n")
        f.write("window.TIMELINE = " + json.dumps(timeline, indent=1) + ";\n")

    n = 0
    with open(os.path.join(HERE, "captions.srt"), "w") as f:
        for s in scenes:
            for l in s["lines"]:
                n += 1
                f.write(f"{n}\n{srt_time(l['start'])} --> {srt_time(l['end'])}\n{l['text']}\n\n")
    print(f"duration {total:.1f}s ({total / 60:.2f} min), {n} lines")


if __name__ == "__main__":
    main(*sys.argv[1:3])
